baseURL = "https://aileenhuang.dev/"
theme = "unrealised"
defaultContentLanguage = "en-nz"

[Languages]
    [Languages.en-nz]
        languageCode = "en-nz"
        title = "Aileen Huang"
        copyright = "© {year} Aileen Huang"
        languageName = "English - New Zealand"
    [Languages.en-nz.params]
        author = "Aileen Huang"
        keywords = "aileen huang, portfolio, web design, web developer, games, software"
        description = "Need a website or app? I optimise for speed while being seamlessly connected to your database & APIs. Contact me today to discuss your project requirements."

[permalinks]
    page = "/:filename"

[params]
    logo = "A HUANG"
    github = "axkeyz"
    linkedin = "aileen-huang"
    pastebin = "https://pastebin.com/u/xah/1/XYjeTSBh"
    email = "/contact"
    enableRobotsTXT = true

[menu]
    [[menu.unrealised]]
        identifier="about-me"
        name="About Me"
    [[menu.unrealised]]
        parent="about-me"
        url="/about"
        name="About Me"
    [[menu.unrealised]]
        parent="about-me"
        url="/blog"
        name="Blog"
    [[menu.unrealised]]
        parent="about-me"
        url="/cv"
        name="CV"
    [[menu.unrealised]]
        identifier="projects"
        name="Projects"
        weight="2"
    [[menu.unrealised]]
        parent="projects"
        url="/projects"
        name="Personal"
    [[menu.unrealised]]
        parent="projects"
        url="/work"
        name="Work"
    [[menu.unrealised]]
        url="/contact"
        name="Contact"
        weight="3"
    [[menu.unrealised]]
        parent="projects"
        url="/sheppa-games"
        name="Sheppa Games"
        