baseURL = "https://aileenhuang.dev/"
theme = "infing"
defaultContentLanguage = "en-nz"
description = "I'm Aileen Huang. I'm a full-stack developer in Auckland, New Zealand. If you need a digital solution, then maybe I can help."

[Languages]
    [Languages.en-nz]
        languageCode = "en-nz"
        title = "Aileen Huang - Web Developer"
        copyright = "© Aileen Huang {year}"
        languageName = "English - New Zealand"
    [Languages.en-nz.params]
        author = "Aileen Huang"
        keywords = "aileen huang, portfolio, web design, web developer, games, software"
        description = "I'm Aileen Huang. I'm a full-stack developer in Auckland, New Zealand. If you need a digital solution, then maybe I can help."
        contact_form_heading = "Contact Me"
        contact_form_description = "If you're interested in hiring me, working together for your next project or something else entirely, feel free to get in touch."

[permalinks]
    page = "/:filename"
    blog = "/blog/:year-:month-:filename"

[params]
    logo = "HUANG"
    github = "axkeyz"
    linkedin = "aileen-huang"
    pastebin = "https://pastebin.com/u/xah/1/XYjeTSBh"
    email = "/contact"
    enableRobotsTXT = true

[menu]
    [[menu.unrealised]]
        url="/projects"
        name="Projects"
        weight=4
    [[menu.unrealised]]
        url="/blog"
        name="Blog"
        weight=5
    [[menu.unrealised]]
        url="#contact-form"
        name="Contact"
        weight=6