baseURL = "https://aileenhuang.dev/"
languageCode = "en-nz"
title = "Aileen's Dump"
theme = "noteworthy"
themesDir = "themes"

[params]
    email = "http://localhost:1313/p/contact/"
    github = "https://github.com/axkeyz"
    linkedin = "https://www.linkedin.com/in/aileen-huang/"

[markup.goldmark.renderer]
    unsafe = true