baseURL = "https://aileenhuang.dev"
theme = "unrealised"
defaultContentLanguage = "en-nz"

[Languages]
    [Languages.en-nz]
        languageCode = "en-nz"
        title = "Aileen Huang"
        copyright = "© {year} Aileen Huang"
        languageName = "English - New Zealand"
    [Languages.en-nz.params]
        author = "Aileen Huang"
        keywords = "aileen huang, portfolio, web design, web developer, games, software"
        description = "Need a website or app? I optimise for speed while being seamlessly connected to your database & APIs. Contact me today to discuss your project requirements."
    [Languages.zh-cn]
        languageCode = "zh-cn"
        title = "黄蔼龄"
        copyright = "© {year} 黄蔼龄"
        languageName = "Chinese - Mandarin"
    [Languages.zh-cn.params]
        author = "黄蔼龄"
        keywords = "黄蔼龄, 简历, 网页设计, 速度优化, 游戏, 软件"
        description = "需要程序或网站吗？我可以帮您链接您的数据库和API或速度优化您的网站。今天就联系我讨论您的项目要求吧。"

[permalinks]
    page = "/:filename"

[params]
    logo = "HUANG"
    github = "axkeyz"
    linkedin = "aileen-huang"
    email = "/contact"
    enableRobotsTXT = true

[menu]
    [[menu.unrealised]]
        identifier="about-me"
        name="svg/identification.html"
    [[menu.unrealised]]
        parent="about-me"
        url="/about"
        name="About Me"
    [[menu.unrealised]]
        parent="about-me"
        url="/blog"
        name="Blog"
    [[menu.unrealised]]
        parent="about-me"
        url="/cv"
        name="CV"
    [[menu.unrealised]]
        identifier="projects"
        name="svg/briefcase.html"
        weight="2"
    [[menu.unrealised]]
        parent="projects"
        url="/projects"
        name="Personal"
    [[menu.unrealised]]
        parent="projects"
        url="/work"
        name="Work"
    [[menu.unrealised]]
        url="/contact"
        name="svg/email.html"
        weight="3"
    [[menu.unrealised]]
        parent="projects"
        url="/sheppa-games"
        name="Sheppa Games"
        