baseURL = "https://aileenhuang.dev/"
theme = "unrealised"
defaultContentLanguage = "en-nz"

[Languages]
    [Languages.en-nz]
        languageCode = "en-nz"
        title = "Aileen Huang"
        copyright = "© {year} Aileen Huang"
        languageName = "English - New Zealand"
    [Languages.en-nz.params]
        author = "Aileen Huang"
        keywords = "aileen huang, portfolio, web design, web developer, games, software"
        description = "Need a website or app? I optimise for speed while being seamlessly connected to your database & APIs. Contact me today to discuss your project requirements."

[permalinks]
    page = "/:filename"
    blog = "/blog/:year/:month/:filename"

[params]
    logo = "HUANG"
    github = "axkeyz"
    linkedin = "aileen-huang"
    pastebin = "https://pastebin.com/u/xah/1/XYjeTSBh"
    email = "/contact"
    enableRobotsTXT = true

[menu]
    [[menu.unrealised]]
        url="/about"
        name="About Me"
        identifier="about"
        weight=1
    [[menu.unrealised]]
        parent="about"
        url="/cv"
        name="Resume"
        weight=2
    [[menu.unrealised]]
        url="/projects"
        name="Projects"
        weight=3
    [[menu.unrealised]]
        url="/blog"
        name="Blog"
        weight=5
    [[menu.unrealised]]
        url="/contact"
        name="Contact"
        weight=6
        